# Generated by Django 5.2 on 2025-05-23 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5, verbose_name='Загадане слово')),
                ('green', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Гра',
                'verbose_name_plural': 'Гри',
            },
        ),
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=5, verbose_name='Хід')),
                ('green', models.PositiveIntegerField(verbose_name='Зелені')),
                ('yellow', models.PositiveIntegerField(verbose_name='Жовті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата спроби')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tries', to='wordle.game', verbose_name='Гра')),
            ],
            options={
                'verbose_name': 'Спроба',
                'verbose_name_plural': 'Спроби',
            },
        ),
    ]
