# Generated by Django 5.2 on 2025-05-01 20:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulls_and_cows', '0002_alter_game_number_alter_try_guess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Гра', 'verbose_name_plural': 'Гри'},
        ),
        migrations.AlterModelOptions(
            name='try',
            options={'verbose_name': 'Спроба', 'verbose_name_plural': 'Спроби'},
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Загадане число'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='try',
            name='bulls',
            field=models.PositiveIntegerField(verbose_name='Бики'),
        ),
        migrations.AlterField(
            model_name='try',
            name='cows',
            field=models.PositiveIntegerField(verbose_name='Корови'),
        ),
        migrations.AlterField(
            model_name='try',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата спроби'),
        ),
        migrations.AlterField(
            model_name='try',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tries', to='bulls_and_cows.game', verbose_name='Гра'),
        ),
        migrations.AlterField(
            model_name='try',
            name='guess',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Хід'),
        ),
    ]
